name    'anl-iptables_persistent'
version '0.0.1'
source 'https://github.com/anl/puppet-iptables_persistent.git'
author 'anl'
license 'Apache License, Version 2.0'
summary 'iptables-persistent module'
description 'Configure iptables'
project_page 'https://github.com/anl/puppet-iptables_persistent'
dependency 'puppetlabs/stdlib', '>= 0.1.1'
